name: rest_api
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.5
  http_interceptor: ^1.0.2
  flutter_slidable: ^2.0.0
  #state management
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5




dev_dependencies:
  flutter_test:
    sdk: flutter
    #state management
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7





  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

